### ISSUE TITLE
WEBEC Assignment 1

### ISSUE THREAD

**Issue by joinutis** [Dierk/WebEngineering-FS19#1]
@Dierk 
Guten Tag, leider bleibe ich beim Import vom Starter Code im Git Classroom hängen. In meinem Profil sehe ich das Repository auch nicht. Brauche Hilfe.

Gruss
Jeremy

**Comment by Dierk** [comment]
wie ist ihr github account Name?

**Comment by Dierk** [comment]
Ihr repository ist hier: https://github.com/WebEngineering-FHNW/fs19-de-graded-exercise-joinutis

**Comment by joinutis** [comment]
Guten Tag Herr König

Vielen Dank hat geklappt.

Gruss
Jeremy

Am Do., 25. Apr. 2019 um 12:09 Uhr schrieb Dierk König <
notifications@github.com>:
